/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ArtistasRouteImport } from './routes/artistas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProfileHandleRouteImport } from './routes/profile/$handle'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as DashboardServiciosRouteImport } from './routes/dashboard/servicios'
import { Route as DashboardPublicarRouteImport } from './routes/dashboard/publicar'
import { Route as DashboardPortafolioRouteImport } from './routes/dashboard/portafolio'
import { Route as DashboardPoliticasRouteImport } from './routes/dashboard/politicas'
import { Route as DashboardFormulariosRouteImport } from './routes/dashboard/formularios'
import { Route as DashboardComisionesRouteImport } from './routes/dashboard/comisiones'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasRoute = ArtistasRouteImport.update({
  id: '/artistas',
  path: '/artistas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/dashboard/wallet',
  path: '/dashboard/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServiciosRoute = DashboardServiciosRouteImport.update({
  id: '/dashboard/servicios',
  path: '/dashboard/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPublicarRoute = DashboardPublicarRouteImport.update({
  id: '/dashboard/publicar',
  path: '/dashboard/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPortafolioRoute = DashboardPortafolioRouteImport.update({
  id: '/dashboard/portafolio',
  path: '/dashboard/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPoliticasRoute = DashboardPoliticasRouteImport.update({
  id: '/dashboard/politicas',
  path: '/dashboard/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFormulariosRoute = DashboardFormulariosRouteImport.update({
  id: '/dashboard/formularios',
  path: '/dashboard/formularios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComisionesRoute = DashboardComisionesRouteImport.update({
  id: '/dashboard/comisiones',
  path: '/dashboard/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artistas': typeof ArtistasRoute
  '/login': typeof LoginRoute
  '/dashboard/comisiones': typeof DashboardComisionesRoute
  '/dashboard/formularios': typeof DashboardFormulariosRoute
  '/dashboard/politicas': typeof DashboardPoliticasRoute
  '/dashboard/portafolio': typeof DashboardPortafolioRoute
  '/dashboard/publicar': typeof DashboardPublicarRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artistas': typeof ArtistasRoute
  '/login': typeof LoginRoute
  '/dashboard/comisiones': typeof DashboardComisionesRoute
  '/dashboard/formularios': typeof DashboardFormulariosRoute
  '/dashboard/politicas': typeof DashboardPoliticasRoute
  '/dashboard/portafolio': typeof DashboardPortafolioRoute
  '/dashboard/publicar': typeof DashboardPublicarRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artistas': typeof ArtistasRoute
  '/login': typeof LoginRoute
  '/dashboard/comisiones': typeof DashboardComisionesRoute
  '/dashboard/formularios': typeof DashboardFormulariosRoute
  '/dashboard/politicas': typeof DashboardPoliticasRoute
  '/dashboard/portafolio': typeof DashboardPortafolioRoute
  '/dashboard/publicar': typeof DashboardPublicarRoute
  '/dashboard/servicios': typeof DashboardServiciosRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artistas'
    | '/login'
    | '/dashboard/comisiones'
    | '/dashboard/formularios'
    | '/dashboard/politicas'
    | '/dashboard/portafolio'
    | '/dashboard/publicar'
    | '/dashboard/servicios'
    | '/dashboard/wallet'
    | '/profile/$handle'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artistas'
    | '/login'
    | '/dashboard/comisiones'
    | '/dashboard/formularios'
    | '/dashboard/politicas'
    | '/dashboard/portafolio'
    | '/dashboard/publicar'
    | '/dashboard/servicios'
    | '/dashboard/wallet'
    | '/profile/$handle'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/artistas'
    | '/login'
    | '/dashboard/comisiones'
    | '/dashboard/formularios'
    | '/dashboard/politicas'
    | '/dashboard/portafolio'
    | '/dashboard/publicar'
    | '/dashboard/servicios'
    | '/dashboard/wallet'
    | '/profile/$handle'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistasRoute: typeof ArtistasRoute
  LoginRoute: typeof LoginRoute
  DashboardComisionesRoute: typeof DashboardComisionesRoute
  DashboardFormulariosRoute: typeof DashboardFormulariosRoute
  DashboardPoliticasRoute: typeof DashboardPoliticasRoute
  DashboardPortafolioRoute: typeof DashboardPortafolioRoute
  DashboardPublicarRoute: typeof DashboardPublicarRoute
  DashboardServiciosRoute: typeof DashboardServiciosRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas': {
      id: '/artistas'
      path: '/artistas'
      fullPath: '/artistas'
      preLoaderRoute: typeof ArtistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servicios': {
      id: '/dashboard/servicios'
      path: '/dashboard/servicios'
      fullPath: '/dashboard/servicios'
      preLoaderRoute: typeof DashboardServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/publicar': {
      id: '/dashboard/publicar'
      path: '/dashboard/publicar'
      fullPath: '/dashboard/publicar'
      preLoaderRoute: typeof DashboardPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/portafolio': {
      id: '/dashboard/portafolio'
      path: '/dashboard/portafolio'
      fullPath: '/dashboard/portafolio'
      preLoaderRoute: typeof DashboardPortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/politicas': {
      id: '/dashboard/politicas'
      path: '/dashboard/politicas'
      fullPath: '/dashboard/politicas'
      preLoaderRoute: typeof DashboardPoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/formularios': {
      id: '/dashboard/formularios'
      path: '/dashboard/formularios'
      fullPath: '/dashboard/formularios'
      preLoaderRoute: typeof DashboardFormulariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/comisiones': {
      id: '/dashboard/comisiones'
      path: '/dashboard/comisiones'
      fullPath: '/dashboard/comisiones'
      preLoaderRoute: typeof DashboardComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistasRoute: ArtistasRoute,
  LoginRoute: LoginRoute,
  DashboardComisionesRoute: DashboardComisionesRoute,
  DashboardFormulariosRoute: DashboardFormulariosRoute,
  DashboardPoliticasRoute: DashboardPoliticasRoute,
  DashboardPortafolioRoute: DashboardPortafolioRoute,
  DashboardPublicarRoute: DashboardPublicarRoute,
  DashboardServiciosRoute: DashboardServiciosRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
